### ISSUE TITLE
Tests failing after PR #67

### ISSUE THREAD

**Issue by ftherrien** [pylada/pylada-light#70]
Some tests are failing since PR #67 (or before?!) 

```
================================== short test summary info ===================================
FAILED tests/decorations/test_defects.py::test_iterator - AttributeError: 'pylada.decorations._decorations.FCIterator' object has no attribute '_FC...
FAILED tests/decorations/test_fciterator.py::test_fciterator - AttributeError: 'pylada.decorations._decorations.FCIterator' object has no attribute '_FC...
FAILED tests/espresso/test_extract.py::test_cellshape - AssertionError: assert False
FAILED tests/espresso/test_pwscf.py::test_iteration - TypeError: __init__() got an unexpected keyword argument 'prefix'
FAILED tests/espresso/bdd/test_restart.py::test_check_restart_input - pylada.error.RuntimeError: Cannot restart from unsuccessful calculation
FAILED tests/espresso/bdd/test_restart.py::test_check_restarted_run - pylada.error.RuntimeError: Cannot restart from unsuccessful calculation
============= 6 failed, 475 passed, 35 skipped, 58 warnings in 74.74s (0:01:14) ==============
```

**Comment by ftherrien** [comment]
To run tests:

```
python -m venv pylada
source pylada/bin/activate
git clone https://github.com/pylada/pylada-light
cd pylada-light
pip install cython setuptools wheel scikit-build cmake ninja numpy pytest pytest-bdd
pip install -e .[dev]
python -m pytest
```
